/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    def filters = {
        all(uri: "/**") {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) return true

                // Access control by convention.
                accessControl()
            }
        }
         adminOnlyForUserManagement(controller:"shiroUser", action:"edit|create|delete") {
            before = {
                accessControl {
                     // Only admins
                     role("Administrator")
                }
            }
        }
        adminOnlyForAdmin(controller:"admin", action:"*") {
            before = {
                accessControl {
                     // Only admins
                     role("Administrator")
                }
            }
        }
        adminOnlyForConfig(controller:"configSetting", action:"*") {
            before = {
                accessControl {
                     role("Administrator")
                }
            }
        }
    }
}
